# Generated by Django 2.2.10 on 2025-09-26 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_auto_20200504_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='code',
            field=models.CharField(blank=True, default='S8887A5', max_length=7, verbose_name='Student code'),
        ),
    ]
