# Generated by Django 2.2.10 on 2025-09-27 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_auto_20250926_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='code',
            field=models.CharField(blank=True, default='S920E21', max_length=7, verbose_name='Student code'),
        ),
    ]
