# Generated by Django 2.2.10 on 2025-09-27 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0009_auto_20250926_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='code',
            field=models.CharField(blank=True, default='TA86741', max_length=7, verbose_name='Teacher code'),
        ),
    ]
