# Generated by Django 2.2.10 on 2025-09-26 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20200504_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, default='AD6ED1', max_length=6, verbose_name='Code'),
        ),
    ]
