# Generated by Django 2.2.10 on 2025-09-27 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20250926_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, default='3FF188', max_length=6, verbose_name='Code'),
        ),
    ]
